// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQ_Urk-1M4hw2m92UOkfaL0HxqFJHMk_k',
    appId: '1:897467470852:web:a11fd63d6e5a5acb965151',
    messagingSenderId: '897467470852',
    projectId: 'yapyap-33bfc',
    authDomain: 'yapyap-33bfc.firebaseapp.com',
    storageBucket: 'yapyap-33bfc.firebasestorage.app',
    measurementId: 'G-P5S3LM400K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVYW9Aep8uQ5rdsjsG0hXrCk3fUyE5Vts',
    appId: '1:897467470852:android:7e89d9cf7e30efea965151',
    messagingSenderId: '897467470852',
    projectId: 'yapyap-33bfc',
    storageBucket: 'yapyap-33bfc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCody21cUhqKxb7fkxY5P0M6783GIZA70Y',
    appId: '1:897467470852:ios:247b5aad7b9858dc965151',
    messagingSenderId: '897467470852',
    projectId: 'yapyap-33bfc',
    storageBucket: 'yapyap-33bfc.firebasestorage.app',
    iosBundleId: 'com.example.yapyap2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCody21cUhqKxb7fkxY5P0M6783GIZA70Y',
    appId: '1:897467470852:ios:247b5aad7b9858dc965151',
    messagingSenderId: '897467470852',
    projectId: 'yapyap-33bfc',
    storageBucket: 'yapyap-33bfc.firebasestorage.app',
    iosBundleId: 'com.example.yapyap2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQ_Urk-1M4hw2m92UOkfaL0HxqFJHMk_k',
    appId: '1:897467470852:web:0117d09e319f7c07965151',
    messagingSenderId: '897467470852',
    projectId: 'yapyap-33bfc',
    authDomain: 'yapyap-33bfc.firebaseapp.com',
    storageBucket: 'yapyap-33bfc.firebasestorage.app',
    measurementId: 'G-5H8XX8049Z',
  );
}
